export default {
  loginBackPad:require('./images/login_back_pad.png'),
  loginBack:require('./images/login_back.png'),
  usr:require('./images/usr.png'),
  ym:require('./images/ic_launcher.png'),
  VRIcon:require('./images/vr.png'),
  develop:require('./images/develop.jpg'),
  error:require('./images/error.jpg'),
  back: require('./images/back.jpg'),
  logo:require('./images/logo.png'),
  ad1: require('./images/ad1.png'),
  ad2: require('./images/ad2@2x.png'),
  avatar: require('./images/avatar.jpg'),
  noData: require('./images/no_log.png'),
  bg: require('./images/bg.jpg'),
  h0: require('./images/h_0.png'),
  h1: require('./images/h_1.png'),
  h2: require('./images/h_2.png'),
  h3: require('./images/h_3.png'),
  h4: require('./images/h_4.png'),
  h5: require('./images/h_5.png'),
  h6: require('./images/h_6.png'),
  h7: require('./images/h_7.png'),
  h8: require('./images/h_8.png'),
  h9: require('./images/h_9.png'),
  h10: require('./images/h_10.png'),
  h11: require('./images/h_11.png'),
  h12: require('./images/h_12.png'),
  h13: require('./images/h_13.png'),
  h14: require('./images/h_14.png'),
  h15: require('./images/h_15.png'),
  hot0: require('./images/hot_0.png'),
  hot1: require('./images/hot_1.png'),
  hot2: require('./images/hot_2.png'),
  hot3: require('./images/hot_3.png'),
  sale0: require('./images/sale_0.png'),
  sale1: require('./images/sale_1.png'),
  sale2: require('./images/sale_2.png'),
  sale3: require('./images/sale_3.png'),
  nice0: require('./images/nice_01.jpg'),
  nice1: require('./images/nice_02.jpg'),
  nice2: require('./images/nice_03.jpg'),
  nice3: require('./images/nice_04.jpg'),
  nice4: require('./images/nice_4.png'),
  nice5: require('./images/nice_5.png'),
  nice6: require('./images/nice_6.png'),
  nice7: require('./images/nice_7.png'),
  coupon0: require('./images/coupon_0.png'),
  coupon1: require('./images/coupon_1.png'),
  star1: require('./images/star.png'),
  star2: require('./images/star-1.png'),
  banner0: require('./images/banner1.png'),
  banner1: require('./images/banner2.png'),
  banner2: require('./images/banner3.png'),
  banner3: require('./images/banner4.png'),
  home1: require('./images/home1.jpg'),
  home2: require('./images/home2.jpg'),
  home3: require('./images/home3.jpg'),
  home4: require('./images/home4.jpg'),
  home5: require('./images/home5.jpg'),
  home6: require('./images/home6.jpg'),
  home7: require('./images/home7.jpg'),
  home8: require('./images/home8.jpg'),
  home9: require('./images/home9.jpg'),
  home10: require('./images/home10.jpg'),
  wechatIcon:require('./images/wechat.png'),
  momentsIcon:require('./images/moment.png'),
  shareIcon:require('./images/share.png')
}
